//! # vaultrs
//!
//! A rust crate for interacting with the Hashicorp Vault API
//!
//! This crate encompasses functions for interacting with the HTTP API available on
//! [Hashicorp Vault](https://!www.vaultproject.io/) servers. It uses
//! [rustify](https://!github.com/jmgilman/rustify) in order to construct accurate
//! representations of each of the endpoints available with the API. It then wraps
//! these into more usable functions intended to be consumed by users of this crate.
//!
//! The following functionality is currently supported:
//!
//! * [PKI Secrets Engine](https://!www.vaultproject.io/docs/secrets/pki)
//!
//! ## Installation
//!
//! ```ignore
//! cargo add vaultrs
//! ```
//!
//! ## Usage
//!
//! ```ignore
//! use vaultrs::api::pki::requests::GenerateCertificateRequest;
//! use vaultrs::client::{VaultClient, VaultClientSettingsBuilder};
//! use vaultrs::kv2;
//! use vaultrs::pki::cert;
//!
//! // Create a client
//! let client = VaultClient::new(
//!     VaultClientSettingsBuilder::default()
//!         .address("https://127.0.0.1:8200")
//!         .token("TOKEN")
//!         .build()
//!         .unwrap()
//! ).unwrap();
//!
//! // Create and read secrets
//! struct MySecret {
//!     key: String,
//!     password: String,
//! }
//!
//! let sec = MySecret {
//!     key: "super".to_string(),
//!     password: "secret".to_string(),
//! };
//! kv2::set(
//!     &client,
//!     "secret",
//!     "mysecret",
//!     &sec,
//! );
//!
//! let sec = kv2::read::<MySecret>(&client, "secret" "mysecret");
//!
//! // Generate a certificate using the PKI backend
//! let cert = cert::generate(
//!     &client,
//!     "pki",
//!     "my_role",
//!     Some(GenerateCertificateRequest::builder().common_name("test.com")),
//! );
//! ```
//!
//! ## Error Handling
//!
//! All errors generated by this crate are wrapped in the `ClientError` enum
//! provided by the crate.
#[macro_use]
extern crate derive_builder;

pub mod api;
pub mod client;
pub mod error;
pub mod kv2;
pub mod pki;
pub mod sys;
