name: Publish Rust Library to AWS CodeArtifact

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::014498626672:role/github-actions-role
          aws-region: eu-central-1

      - name: Publish Rust Crate
        run: cargo publish --registry dataspine --allow-dirty